# -*- coding: utf-8 -*-
"""Business Analytics Internship

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mDvm2-gicQ4_9NLGM9pYpjmY9nigDyCw
"""

from google.colab import files

# Upload the dataset file
uploaded = files.upload()

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
import io
df = pd.read_csv(io.BytesIO(uploaded['AB_NYC_2019.csv']))

# Data Exploration
print(df.head())
print(df.info())
print(df.describe())

# Handling Missing Values
print(df.isnull().sum())

# Data Visualization
plt.figure(figsize=(10, 6))
sns.histplot(df['price'], bins=30, kde=True)
plt.title('Distribution of Prices')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='number_of_reviews', y='price', data=df)
plt.title('Price vs. Number of Reviews')
plt.xlabel('Number of Reviews')
plt.ylabel('Price')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='room_type', y='price', data=df)
plt.title('Price by Room Type')
plt.xlabel('Room Type')
plt.ylabel('Price')
plt.show()

# Exclude non-numeric columns
numeric_columns = df.select_dtypes(include=[np.number])

# Correlation Analysis
corr_matrix = numeric_columns.corr()
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation Matrix')
plt.show()